config/routes.rb
AlingnenaApp::Application.routes.draw do
  resources :customers

  resources :messages do
    collection do
      get 'message_table'
    end
  end

  resources :suppliers

  resources :purchases do
    resource :invoice
    resources :line_items
  end 

  resources :debts

  resources :products do
    collection do
      get 'search'
    end
  end
end

app/models/debt.rb
class Debt < ActiveRecord::Base
end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController
  before_action :set_debt, only: [:show, :edit, :update, :destroy]

  # GET /debts
  # GET /debts.json
  def index
    @debts = Debt.all
  end

  # GET /debts/1
  # GET /debts/1.json
  def show
  end

  # GET /debts/new
  def new
    @debt = Debt.new
  end

  # GET /debts/1/edit
  def edit
  end

  # POST /debts
  # POST /debts.json
  def create
    @debt = Debt.new(debt_params)

    respond_to do |format|
      if @debt.save
        format.html { redirect_to @debt, notice: 'Debt was successfully created.' }
        format.json { render action: 'show', status: :created, location: @debt }
      else
        format.html { render action: 'new' }
        format.json { render json: @debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debts/1
  # PATCH/PUT /debts/1.json
  def update
    respond_to do |format|
      if @debt.update(debt_params)
        format.html { redirect_to @debt, notice: 'Debt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debts/1
  # DELETE /debts/1.json
  def destroy
    @debt.destroy
    respond_to do |format|
      format.html { redirect_to debts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debt
      @debt = Debt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def debt_params
      params.require(:debt).permit(:name, :item, :amount, :remarks)
    end
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/views/debts/_form.html.erb
<%= form_for(@debt) do |f| %>
  <% if @debt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@debt.errors.count, "error") %> prohibited this debt from being saved:</h2>

      <ul>
      <% @debt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :item %><br>
    <%= f.text_area :item %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :remarks %><br>
    <%= f.text_area :remarks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/debts/edit.html.erb
<h1>Editing debt</h1>

<%= render 'form' %>

<%= link_to 'Show', @debt %> |
<%= link_to 'Back', debts_path %>

app/views/debts/index.html.erb
<h1>Listing debts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Item</th>
      <th>Amount</th>
      <th>Remarks</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @debts.each do |debt| %>
      <tr>
        <td><%= debt.name %></td>
        <td><%= debt.item %></td>
        <td><%= debt.amount %></td>
        <td><%= debt.remarks %></td>
        <td><%= link_to 'Show', debt %></td>
        <td><%= link_to 'Edit', edit_debt_path(debt) %></td>
        <td><%= link_to 'Destroy', debt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Debt', new_debt_path %>

app/views/debts/new.html.erb
<h1>New debt</h1>

<%= render 'form' %>

<%= link_to 'Back', debts_path %>

app/views/debts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @debt.name %>
</p>

<p>
  <strong>Item:</strong>
  <%= @debt.item %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @debt.amount %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @debt.remarks %>
</p>

<%= link_to 'Edit', edit_debt_path(@debt) %> |
<%= link_to 'Back', debts_path %>