config/routes.rb
AlingnenaApp::Application.routes.draw do
  resources :customers

  resources :messages do
    collection do
      get 'message_table'
    end
  end

  resources :suppliers

  resources :purchases do
    resource :invoice
    resources :line_items
  end 

  resources :debts

  resources :products do
    collection do
      get 'search'
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  has_many :line_items
  has_many :purchases, -> { uniq }, through: :line_items

  before_validation :assign_default_description

  private

    def assign_default_description
      if description.blank?
        self.description = name
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :check_if_aling_nena, :except => [:index, :show, :search]

  def index
    @products = Product.all
  end

  def search
    @products = Product.find_all_by_name(params[:name])
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(params.require(:product)
                                 .permit(:name, :description, :cost, :stock))
    if @product.save
      redirect_to @product, notice: "Product has been successfully created."
    else 
      render action: "new"
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params.require(:product)
                                 .permit(:name, :description, :cost, :stock))
      redirect_to @product, notice: 'Product was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, notice: "Product was successfully deleted."
  end

  private

    def check_if_aling_nena
      authenticate_or_request_with_http_basic("Products Realm") do |username, password|
        username == "admin" and password == "sTr0NG_p4$swOrD"
      end
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for product do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= t "activerecord.errors.template.header", count: product.errors.count, 
                model: product.class.model_name.human.downcase %>:</h2>
      <ul>
      <% product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :stock %><br />
    <%= f.text_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit button_label %>
  </div>
<% end %>

app/views/products/_hr.html.erb
<tr><td colspan="7"><hr></td></tr>

app/views/products/_item.html.erb
<tr>
  <td><%= item.name %></td>
  <td><%= item.description %></td>
  <td><%= number_to_currency item.cost, unit: 'PhP' %></td>
  <td><%= item.stock %></td>
  <td><%= link_to 'Show', item %></td>
  <td><%= link_to 'Edit', edit_product_path(item) %></td>
</tr>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form", product: @product, button_label: "Update" %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= flash[:notice] %></p>

<%= form_tag search_products_path, method: :get do %>
  <%= label_tag "name", "Search by product name:" %>
  <%= text_field_tag "name" %>
  <%= submit_tag"Search" %>
<% end %>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Cost</th>
      <th>Stock</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "item", collection: @products, spacer_template: "hr" %>
  </tbody>
</table>

<p><%= link_to "Create a new Product", new_product_path %></p>

app/views/products/new.html.erb
<h1><%=t 'views.product.header.new' %></h1>

<%= render "form", product: @product, button_label: t('views.button.create') %>

<%= link_to t('views.link.back'), products_path %>  

app/views/products/search.html.erb
<h1>Listing Products</h1>

<p>Displaying Products with name "<%= params[:name] %>"</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Cost</th>
      <th>Stock</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= number_to_currency product.cost, unit: "PhP" %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Show', product %></td>
      </tr>
    <% end %>  
  </tbody>
</table>

<p><%= link_to "Back to original list", products_path %></p>

app/views/products/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<h1><%=t "views.product.header.show" %></h1>
<p>
  <strong><%= label(:product, :name) %>:</strong>
  <%= @product.name %>
</p>
<p>
  <strong><%= label(:product, :description) %>:</strong>
  <%= @product.description %>
</p>
<p>
  <strong><%= label(:product, :cost) %>:</strong>
  <%= number_to_currency @product.cost %>
</p>
<p>
  <strong><%= label(:product, :stock) %>:</strong>
  <%= number_with_delimiter @product.stock %>
</p>
<p>
  <strong><%= label(:product, :created_at) %>:</strong>
  <%=l @product.created_at %>
</p>

<h2>Related Purchases</h2>
<ul>
  <% @product.purchases.each do |purchase| %>
    <li><%= link_to purchase.description, purchase %></li>
  <% end %>
</ul>

<%= link_to 'Edit this record', edit_product_path(@product) %> <br>
<%= link_to 'Delete this record', @product,  
    data: { confirm: 'Are you sure?' }, method: :delete %> <br>
<%= link_to 'Back to List of Products', products_path %>