config/routes.rb
AlingnenaApp::Application.routes.draw do
  resources :customers

  resources :messages do
    collection do
      get 'message_table'
    end
  end

  resources :suppliers

  resources :purchases do
    resource :invoice
    resources :line_items
  end 

  resources :debts

  resources :products do
    collection do
      get 'search'
    end
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :purchase
  belongs_to :product
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:edit, :update, :destroy]

  def index
    # integrate with show purchase
    redirect_to Purchase.find(params[:purchase_id])
  end

  def show
    # integrate with show purchase
    redirect_to Purchase.find(params[:purchase_id])
  end

  def new
    @purchase = Purchase.find(params[:purchase_id])
    @line_item = @purchase.line_items.build
  end

  def edit
  end

  def create
    @purchase = Purchase.find(params[:purchase_id])
    @line_item = @purchase.line_items.build(line_item_params)
    if @line_item.save
      redirect_to @purchase, notice: 'Line Item was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    if @line_item.update_attributes(line_item_params)
      redirect_to @purchase, notice: 'Line Item was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @line_item.destroy
    redirect_to @purchase, notice: 'Line Item was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @purchase = Purchase.find(params[:purchase_id])
      @line_item = @purchase.line_items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :quantity, :cost)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for([purchase, line_item]) do |f| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this Line Item
        from being saved:</h2>
      <ul>
      <% line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Purchase</label><br>
    <%= purchase.description %>
  </div>
  <div class="field">
    <%= f.label :product_id, "Product" %><br>
    <%= f.collection_select :product_id, Product.all, :id, :name, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', purchase %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', purchase: @purchase, line_item: @line_item %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Purchase</th>
      <th>Product</th>
      <th>Quantity</th>
      <th>Cost</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.purchase %></td>
        <td><%= line_item.product %></td>
        <td><%= line_item.quantity %></td>
        <td><%= line_item.cost %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', purchase: @purchase, line_item: @line_item %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Purchase:</strong>
  <%= @line_item.purchase %>
</p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @line_item.quantity %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @line_item.cost %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>